### ISSUE TITLE
Source file for the case

### ISSUE THREAD

**Issue by dgrabla** [methodpark/ParkDeck#1]
Terrific project, thanks

Hey @LeJokester any chance we can get a step file || onshape link || fusion360 to do remixes of the case? 
I would like to hook it somehow under the display and use it 'upside down'. 
I could not find the model on printables or thingiverse.

Best

**Comment by LeJokester** [comment]
Glad you like it! I added the case model as step and fbx files, I hope that helps :)

**Comment by dgrabla** [comment]
Great, thanks!
